"""Added postgresql 2

Revision ID: 171fbf4a1f83
Revises: 4ab6608cb72b
Create Date: 2021-08-31 22:59:28.635104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171fbf4a1f83'
down_revision = '4ab6608cb72b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
