"""Added postgresql

Revision ID: 4ab6608cb72b
Revises: 8b8076ff1a6b
Create Date: 2021-08-31 22:56:37.880179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab6608cb72b'
down_revision = '8b8076ff1a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
