"""Fix PrivateChatRoom table

Revision ID: 4cfde2512cb4
Revises: ece80e569903
Create Date: 2021-08-27 19:30:12.252897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cfde2512cb4'
down_revision = 'ece80e569903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
