"""MOD database url

Revision ID: 8b8076ff1a6b
Revises: cb740e07f32d
Create Date: 2021-08-28 11:57:38.168356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b8076ff1a6b'
down_revision = 'cb740e07f32d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
