"""Added postgresql 3

Revision ID: a0ad0d112046
Revises: 171fbf4a1f83
Create Date: 2021-08-31 23:00:49.912836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ad0d112046'
down_revision = '171fbf4a1f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
