"""Fix PrivateChatRoom table

Revision ID: cb740e07f32d
Revises: 4cfde2512cb4
Create Date: 2021-08-27 19:35:41.298032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb740e07f32d'
down_revision = '4cfde2512cb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
