"""Fix PrivateChatRoom table

Revision ID: ece80e569903
Revises: 9ea86416ffcd
Create Date: 2021-08-27 19:14:02.057985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece80e569903'
down_revision = '9ea86416ffcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
